### ISSUE TITLE
Release Managerによって作成されたリリースではon: releaseのactionsが起動しない

### ISSUE THREAD

**Issue by tamaina** [joinmisskey/release-actions#26]
なんで？

**Comment by anatawa12** [comment]
github actionsの仕様ですね。
日本語は訳が支離滅裂だったので英語で引用

> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. 
> For example, if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.

回避策として独自のGitHub appとしてworkflowから振る舞うのが提示されてますね。

https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow

**Comment by tamaina** [comment]
リリースも一律でダメなんだなぁ

**Comment by tamaina** [comment]
App別に作る以外に、ローカルへの参照としてworkflow_callをするのも考えられるけど…

**Comment by tamaina** [comment]
eventsが使い物にならないからナシで

**Comment by tamaina** [comment]
アプリを指定するようにした
